site_name: WAGGON
markdown_extensions:
  - markdown_include.include
  - extra
  - tables
  - mdx_math:
      enable_dollar_delimiter: True
  - fenced_code
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
nav:
  - Home: index.md
  - Black-box optimisation: about.md
  - Optimisation:
    - Optimiser: optim.md
    - Surrogate based optimisation: surr_opt.md
  - Surrogates:
    - Surrogate-based Optimisation: surr.md
    - Deep Generative Surrogates: dgm.md
    - Bayesian Neural Networks: bnn.md
    - Deep Adversarial Ensembles: de.md
    - Deep Gaussian Processes: dgp.md
    - Gaussian Processes: gp.md
  - Acquisition Functions:
    - Wasserstein Uncertainty: wu.md
    - Expected Improvement: ei.md
    - Confidence Bound: cb.md
    - Custom Acquisition Functions: custom_acqf.md
  - Experiments:
    - Test functions: functions.md
    - Custom experiments: custom_exp.md

theme: readthedocs
