site_name: WAGGON
markdown_extensions:
  - extra
  - tables
  - fenced_code
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
nav:
  - Home: index.md
  - Black-box optimisation: about.md
  - Optimisation:
    - Optimiser: optim.md
    - Surrogate based optimisation: surr_opt.md
  - Surrogates:
    - Deep Generative Surrogates: dgm.md
    - Bayesian Neural Networks: bnn.md
    - Deep Adversarial Ensembles: de.md
    - Deep Gaussian Processes: dgp.md
    - Gaussian Processes: gp.md
    - Custom Surrogates: custom_surr.md
  - Acquisition Functions:
    - Wasserstein Uncertainty: wu.md
    - Expected Improvement: ei.md
    - Confidence Bound: cb.md
    - Custom Acquisition Functions: custom_acqf.md
  - Experiments:
    - Test functions: functions.md
    - Custom experiments: custom_exp.md

theme: readthedocs